#!/bin/bash
cat << EOF > kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cortex
nodes:
- role: control-plane
- role: worker
- role: worker
EOF

# Create the Kind cluster
kind create cluster --config=kind-config.yaml

# Verify the cluster
kubectl cluster-info

# Check the nodes
kubectl get nodes

echo "Kind cluster with 3 nodes created!"

# Install Prometheus with Helm chart
kubectl create namespace cortex
helm repo add stable https://charts.helm.sh/stable
helm repo update
helm install stable prometheus-community/kube-prometheus-stack 

# Verify Prometheus installation
kubectl get pods 
echo "Waiting for Prometheus pod to be ready..."
kubectl wait --for=condition=Ready pod -l app=prom-app --timeout=300s

echo "Prometheus pod is up and running!"
echo "Prometheus installed on the Kind cluster using Helm chart!"

helm repo add hashicorp https://helm.releases.hashicorp.com
helm search repo hashicorp/consul
helm install consul hashicorp/consul --set global.name=consul --namespace cortex

cat << EOF > values.yaml
config:
  ruler:
    enable_api: true
    rule_path: /rules
  alertmanager:
    enable_api: true
    data_dir: /data

  auth_enabled: true
  api:
    prometheus_http_prefix: '/prometheus'
    response_compression_enabled: true
  ingester:
    lifecycler:
      join_after: 0s
      final_sleep: 0s
      num_tokens: 512
      ring:
        replication_factor: 3
        kvstore:
          store: consul
          prefix: 'collectors/'
          consul:
            host: 'consul-server:8500'
            http_client_timeout: '20s'
            consistent_reads: true
  ruler_storage:
    backend: s3
    s3:
      bucket_name: cortex-buc
      access_key_id: AKIA
      secret_access_key: E3GVV
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1
  alertmanager_storage:
    backend: s3
    s3:
      bucket_name: cortex-buc
      access_key_id: AK
      secret_access_key: E3
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1

  storage:
    engine: blocks
  blocks_storage:
    backend: s3
    s3:
      bucket_name: cortex-buc
      access_key_id: AKIA
      secret_access_key: E3G
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1

    bucket_store:
      sync_dir: "/data"
    tsdb:
      dir: "/data"

alertmanager:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom

distributor:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom

ingester:
  autoforget_unhealthy: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom

ruler:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom

querier:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom

query_frontend:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom

nginx:
  service:
    type: LoadBalancer
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom

store_gateway:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom

compactor:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom
EOF
helm repo add cortex-helm https://cortexproject.github.io/cortex-helm-chart
helm repo update
helm install cortex --namespace cortex -f values.yaml cortex-helm/cortex

cat << EOF > rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
EOF
cat << EOF > prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prom-app
  namespace: default
spec:
  enableAdminAPI: false
  image: quay.io/prometheus/prometheus:v2.28.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: prom
  portName: web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: prom
  remoteWrite:
  - url: http://cortex-nginx.cortex/api/prom/push
    headers:
      X-Scope-OrgID: fake
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: kube-prometheus-stack
      release: prom
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prom
  shards: 1
  version: v2.28.1
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-app
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9092
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prom-app
EOF
kubectl apply -f rbac.yaml
kubectl apply -f prometheus.yaml
